### ISSUE TITLE
newItem.push is not a function

### ISSUE THREAD

**Issue by yurifontoura** [zoeyg/binance#87]
c:\Users\Administrator\Documents\javascript\node_modules\binance\lib\beautifier.js:215
                        newItem.push(
                                ^

TypeError: newItem.push is not a function
    at c:\Users\Administrator\Documents\javascript\node_modules\binance\lib\beautifier.js:215:33
    at Function.each (c:\Users\Administrator\Documents\javascript\node_modules\underscore\underscore.js:188:9)
    at c:\Users\Administrator\Documents\javascript\node_modules\binance\lib\beautifier.js:214:23
    at Function.each (c:\Users\Administrator\Documents\javascript\node_modules\underscore\underscore.js:193:9)
    at Beautifier.beautify (c:\Users\Administrator\Documents\javascript\node_modules\binance\lib\beautifier.js:200:11)
    at BinanceWS._beautifyResponse (c:\Users\Administrator\Documents\javascript\node_modules\binance\lib\ws.js:77:37)
    at WebSocket.<anonymous> (c:\Users\Administrator\Documents\javascript\node_modules\binance\lib\ws.js:54:34)
    at WebSocket.emit (events.js:210:5)
    at Receiver._receiver.onmessage (c:\Users\Administrator\Documents\javascript\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (c:\Users\Administrator\Documents\javascript\node_modules\ws\lib\Receiver.js:389:14)

After yesterday binance mainteance Im getting this error.

**Comment by tiagosiebler** [comment]
Interesting, happened too but only with some of my instances. Seems it was while binance APIs were returning 502 bad gateway errors. I don't think it's a permanent issue, my logs only show this while binance was giving errors / down for maintenance.

Might be a typo here:
https://github.com/zoeyg/binance/blob/master/lib/beautifier.js#L215

@zoeyg should that be `newArray` instead of `newItem`?

**Comment by NeverEnder4** [comment]
@tiagosiebler @yurifontoura, the issue is most likely that newItem.push should in fact be newArray.push. I made the changes in my node modules and tested it out in my application and the package is now working again.

newItem is initialized as an object, hence the `TypeError: newItem.push is not a function`.
